In [3]:
import gspread
import pandas as pd
from datetime import datetime
gc = gspread.service_account(filename="DSSheetprathmesh.json")
wks = gc.open("ProjectWorkDS").worksheet("ALLDATA")
values = wks.get_all_values()
headers = values[0]
df = pd.DataFrame(values[1:], columns=headers)
df

,टाइमस्टँप,कुटुंब प्रमुखाचे नावं,जन्म तारीख,लिंग,मोबाईल क्रमांक,शिक्षण,नोकरी / व्यवसाय,व्यवसायाचा प्रकार / नाव,सध्या तुम्ही कुठे राहता? कृपया गावाचे नाव लिहा.,विकलांग ?,...,नोकरी / व्यवसाय,व्यवसायाचा प्रकार / नाव,सध्या तुम्ही कुठे राहता? कृपया गावाचे नाव लिहा.,विकलांग ?,पेंशन मिळते का ?,विधवा आहे का ?,परितक्त्या आहे का ?,दुर्दर आजार आहे का ?,अजून कुटुंब सदस्य जोडायचा आहे का ?,
0,0,1,2,3,4,5,6,7,8,9,...,179,180,181,182,183,184,185,186,187,188
1,5/18/2023 22:08:10,नेताजी कुंडलिक पाटील,7/1/1974,पुरुष,9921111414,BA / BCOM / BSC,शेती,,मांगोली,नाही,...,,,,,,,,,,
2,5/24/2023 18:14:28,बंडा बापू आरडे,12/25/1950,पुरुष,9689943152,दहावी,रिटायर्ड,,मांगोली,नाही,...,,,,,,,,,,
3,5/24/2023 18:26:53,संजय धोंडीराम रेपे,3/20/1970,पुरुष,9687317059,,शेती,,मांगोली,नाही,...,,,,,,,,,,
4,5/24/2023 18:39:00,मधुकर लक्ष्मण कुंभार,6/1/1966,पुरुष,9405014936,दहावी पेक्षा कमी,शेती,,मांगोली,नाही,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,8/2/2023 10:24:56,उत्तम महादेव कुंभार,10/18/1975,पुरुष,97 65 83 15 27,बारावी,शेती,,मांगोली,नाही,...,,,,,,,,,,
301,8/2/2023 10:32:40,मिलिंद नानाजी कुंभार,8/1/1979,पुरुष,85 50 935 507,बारावी,शेती,,मंगोली,नाही,...,,,,,,,,,,
302,8/2/2023 10:35:50,बाजीराव विष्णू पाटील,6/1/1972,पुरुष,9049228177,दहावी,व्यवसाय,बर्फी व्यवसाय,मांगोली,नाही,...,,,,,,,,,,
303,8/2/2023 10:42:48,महिपती दत्तात्रय कुंभार,2/20/1949,पुरुष,80 88 18 77 99,दहावी पेक्षा कमी,शेती,,मांगोली,नाही,...,,,,,,,,,,
304,8/2/2023 10:50:32,शंकर आण्णाप्पा वरुटे,6/1/1952,पुरुष,8806291616,अशिक्षीत,शेती,,मांगोली,हो,...,,,,,,,,,,

In [6]:
familyhead = df.iloc[1:, 2:3]  
familyhead

    जन्म तारीख
1       7/1/1974
2     12/25/1950
3      3/20/1970
4       6/1/1966
5       6/1/1954
..           ...
300   10/18/1975
301     8/1/1979
302     6/1/1972
303    2/20/1949
304     6/1/1952

[304 rows x 1 columns]

In [11]:
import pandas as pd
from datetime import datetime

# Sample data
data = df.iloc[1:, 2:3]

df = pd.DataFrame(data)

# Function to calculate age
def calculate_age(birthdate):
    try:
        birthdate = datetime.strptime(birthdate, '%Y-%m-%d')
        today = datetime.today()
        age = today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))
        return age
    except:
        return 'UNKNOWN'

# Apply the calculate_age function to the Birthdate column and create a new 'Age' column
df['Age'] = df.iloc[1:, 2:3].apply(calculate_age)

# Calculate age distribution
age_counts = df['Age'].value_counts().sort_index()
print(age_counts)

# Find data using index
def findDataUsingIndex(index):
    column_heading = df.columns[index]
    value_counts = df.iloc[:, index].value_counts()
    
    values = {}
    for value, count in value_counts.items():
        value = value if pd.notnull(value) else 'UNKNOWN'
        values[value] = count

    print(f"Column: {column_heading}")
    print(values)

findDataUsingIndex(1)  # Replace 1 with the desired column index

Series([], Name: count, dtype: int64)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [14]:
# find the data using index and calculate
def findDataUsingIndex(index):
    datasystem_counts = df.iloc[:, index].value_counts()
    # print("datasystem_counts",datasystem_counts)
    column_heading = df.columns[index]
    column_heading={}
    for value, count in datasystem_counts.items():
        value = value if value else 'UNKNOWN'    
        column_heading[value] = count

    print(column_heading)

findDataUsingIndex(18)
findDataUsingIndex(19)

IndexError: single positional indexer is out-of-bounds